@startuml
'https://plantuml.com/use-case-diagram

  actor user

  usecase "StartMenu" as UC1
  usecase "CreateUser" as UC2
  usecase "Login" as UC3
  usecase "MenuOptions" as UC4
  usecase "Search" as UC5
  usecase "Restaurant" as UC6
  usecase "Category" as UC7
  usecase "Order" as UC8
  usecase "ShowSavedOrdreHistory" as UC9
  usecase "LogOut" as UC10


user --> UC1
UC1 --> UC9
UC1 --> UC2
UC1 --> UC10
UC2 --> UC3
UC1 --> UC3
UC3 --> UC4
UC3 --> UC10
UC4 --> UC5
UC5 --> UC6
UC6 --> UC8
UC5 --> UC7
UC7 --> UC8
UC4 --> UC9





@enduml


